#!/bin/bash

echo "🔧 AluVerse SSH Deployment Setup"
echo "================================"
echo ""

# Check if SSH key exists
if [ ! -f ~/.ssh/id_rsa.pub ]; then
    echo "🔑 Generating SSH key..."
    ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
    echo "✅ SSH key generated!"
    echo ""
    echo "📋 Add this public key to your server:"
    echo "cat ~/.ssh/id_rsa.pub"
    echo ""
    echo "💡 On your server, add it to ~/.ssh/authorized_keys"
    echo ""
else
    echo "✅ SSH key already exists"
fi

echo "🔍 Your public key:"
echo "-----------------"
cat ~/.ssh/id_rsa.pub
echo "-----------------"
echo ""

echo "📋 Server Setup Commands:"
echo "========================="
echo "# 1. Update your server"
echo "sudo apt update && sudo apt upgrade -y"
echo ""
echo "# 2. Install Node.js and npm"
echo "curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
echo "sudo apt-get install -y nodejs"
echo ""
echo "# 3. Install nginx"
echo "sudo apt install -y nginx"
echo ""
echo "# 4. Create deployment directory"
echo "sudo mkdir -p /var/www/aliverse"
echo "sudo chown -R \$USER:\$USER /var/www/aliverse"
echo ""
echo "# 5. Copy nginx config"
echo "sudo cp nginx.conf /etc/nginx/sites-available/aliverse"
echo "sudo ln -s /etc/nginx/sites-available/aliverse /etc/nginx/sites-enabled/"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "# 6. Add your SSH public key to authorized_keys"
echo "echo 'YOUR_PUBLIC_KEY_HERE' >> ~/.ssh/authorized_keys"
echo ""
echo "🔧 Update deploy-ssh.sh with your server details:"
echo "- SERVER_HOST=YOUR_ACTUAL_SERVER_IP"
echo "- SERVER_USER=your_username"
echo ""
echo "🎉 Then run: ./deploy-ssh.sh"
